// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ozcq8GxerrF1WYaqjsW34y
// Component: Ydqp5FxoI2V8ei
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header2 from "../../Header2"; // plasmic-import: zrbm_cXqG-RFfk/component
import ProductCard from "../../ProductCard"; // plasmic-import: Pn5M_QzIQn7ZB3/component
import Ratings from "../../Ratings"; // plasmic-import: 9S_qTaYwkjYj0t/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: 0qu_kH_ddiMZdR/component
import BlogPost from "../../BlogPost"; // plasmic-import: OzNhyBBwnUWeMi/component
import Footer from "../../Footer"; // plasmic-import: Ds72FX0K-kOF2Y/component
import ProductRow from "../../ProductRow"; // plasmic-import: keSq6YDh49oPso/component
import { useScreenVariants as useScreenVariantssOxgEMpX5WMfyx } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: sOxgEMpX5wMfyx/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: ozcq8GxerrF1WYaqjsW34y/projectcss
import sty from "./PlasmicStore.module.css"; // plasmic-import: Ydqp5FxoI2V8ei/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: le9jVYTVBu1qJc/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: N3zuMpArvgBzsN/icon
import galinaNMiziNqvJx5MUnsplashjpgARAirbMaCfir from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: A_rAIRB_maCFIR/picture
import igorSonFvPxCqgtwcUnsplashjpgO3KFr3VQ40RKOw from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: o3KFr3vQ40rKOw/picture
import scottWebbORwRlTgBrPoUnsplashjpgZt1MhIquN0B9Dk from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: ZT1MHIquN0B9Dk/picture
import freddieMarriageUcfKyTanLuUnsplashjpg69MtM6AxIZnF from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: 69mtM6ax-I_ZnF/picture
import f2Ijq0BYlEpgjyWy from "./images/f2.jpg"; // plasmic-import: ijq0BYlEpgjyWY/picture
import f3VGdmatAkcDt6OJ from "./images/f3.jpg"; // plasmic-import: VGdmatAkcDT6oJ/picture
import f4LrXqDp5TuHj5I from "./images/f4.jpg"; // plasmic-import: lrXQDp5_TuHJ5I/picture
import b1Gc8XZuPeE3Xri from "./images/b1.jpg"; // plasmic-import: gc8xZuPE-E3XRI/picture
import b2ZsFejOqYuGucyL from "./images/b2.jpg"; // plasmic-import: ZSFejOqYuGucyL/picture
import b3ZPeaqAnQLspkp from "./images/b3.jpg"; // plasmic-import: zPeaqAnQ-lspkp/picture
import adidasZyTCRzQd1XP2U from "./images/adidas.png"; // plasmic-import: ZyT-CRzQD1xP2u/picture
import hmUs3NPrvBl7Czal from "./images/hm.png"; // plasmic-import: Us3NPrvBL7CZAL/picture
import kappa6Knw5HlG0NoZmC from "./images/kappa.png"; // plasmic-import: 6KNW5HlG0NOZmC/picture
import lacosteNuYyWlf4Zl1Cxa from "./images/lacoste.png"; // plasmic-import: NUYyWLF4ZL1cxa/picture
import levisNqr00Qq1MYrLBa from "./images/levis.png"; // plasmic-import: Nqr00QQ1MYrLBa/picture
import plant6JpgC6L1C8MPjCoBpj from "./images/plant6Jpg.png"; // plasmic-import: C6L1C8MPjCoBPJ/picture
import plant1JpgJur1RNKmGbilj from "./images/plant1Jpg.png"; // plasmic-import: Jur1-rNKmGbilj/picture
import plant5JpgSC9Dn8R35Vnpr from "./images/plant5Jpg.png"; // plasmic-import: s_c9DN8r35vnpr/picture
import plant7JpgFY6MVzsllwIo2L from "./images/plant7Jpg.png"; // plasmic-import: fY6mVzsllwIo2l/picture
import plant2WebpSbSmpYgIseSxK from "./images/plant2Webp.webp"; // plasmic-import: SBSmpYGIseSx-k/picture
import plant41JpgPDx9Qa5KrKmFe from "./images/plant41Jpg.png"; // plasmic-import: pDX9Qa5KrKmFe_/picture
import plant31JpgVmNfGCgklisJox from "./images/plant31Jpg.png"; // plasmic-import: VmNfGCgklisJox/picture
import plant9WebpKV5HjHwju5Oi from "./images/plant9Webp.webp"; // plasmic-import: kV5-HJ_hwju5Oi/picture

export const PlasmicStore__VariantProps = new Array();

export const PlasmicStore__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicStore__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantssOxgEMpX5WMfyx()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__iet6V)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___4D7A8)}>
                {true ? (
                  <Header2
                    data-plasmic-name={"header2"}
                    data-plasmic-override={overrides.header2}
                    className={classNames("__wab_instance", sty.header2)}
                  />
                ) : null}
              </div>
            </p.Stack>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__j1WPh)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__dcw8I
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___7Xmla)}
              >
                <div className={classNames(projectcss.all, sty.column___9Xrkl)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__qdU6L
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ptxAm)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: galinaNMiziNqvJx5MUnsplashjpgARAirbMaCfir,
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__f1VOy
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__ajaaV)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__i4Irr
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___9WmbF)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: igorSonFvPxCqgtwcUnsplashjpgO3KFr3VQ40RKOw,
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___7VXq4
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__enhj8)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__hGlaW
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hrddi)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: scottWebbORwRlTgBrPoUnsplashjpgZt1MhIquN0B9Dk,
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__m5Duo
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__wWVqR)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__aORnT
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__miG45)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: freddieMarriageUcfKyTanLuUnsplashjpg69MtM6AxIZnF,
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__bOrhb
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox___2HIri)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2JXhT
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__cBmfq)}
              >
                <div className={classNames(projectcss.all, sty.column__qSJws)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__gOtiN
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__obH5
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__z04Pb
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two"}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__moCpp
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__dtmul)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__jdy0Z
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__yc6A4)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f2Ijq0BYlEpgjyWy,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__fA3Yd
                        )}
                        stars={"four"}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__fnjPy)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__hKfmH
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__a7G)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f3VGdmatAkcDt6OJ,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___1Lt4Q
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five"}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__nEPyc)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__rHhYd
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__eyJmW)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f4LrXqDp5TuHj5I,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__puOoR
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__wBpOb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x4W77
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___3CecO)}
              >
                <div className={classNames(projectcss.all, sty.column__jqAgn)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost___0AtNd
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__u9Vj)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b1Gc8XZuPeE3Xri,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__o3UyS)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__dm9Oq
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___30Bl)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b2ZsFejOqYuGucyL,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__eZfMe)}>
                  <BlogPost
                    className={classNames("__wab_instance", sty.blogPost__iz7A)}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__n4L7M)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b3ZPeaqAnQLspkp,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__oj7Ua)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__euXCd)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  src={{
                    src: adidasZyTCRzQd1XP2U,
                    fullWidth: 90,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dAxol)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"91px"}
                  src={{
                    src: hmUs3NPrvBl7Czal,
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__lZt6Y)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"98px"}
                  src={{
                    src: kappa6Knw5HlG0NoZmC,
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nVYuB)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"124px"}
                  src={{
                    src: lacosteNuYyWlf4Zl1Cxa,
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bDbOx)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"125px"}
                  src={{
                    src: levisNqr00Qq1MYrLBa,
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__xvRtL)}
              />
            ) : null}
          </div>
          {true ? (
            <div
              data-plasmic-name={"allProduct"}
              data-plasmic-override={overrides.allProduct}
              className={classNames(projectcss.all, sty.allProduct)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2Dk9C)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__oUa1
                    )}
                  >
                    {"All Products"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__z9Wvp)}
              >
                <div className={classNames(projectcss.all, sty.column__gcEix)}>
                  {true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9OIgR
                      )}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bDqJ3
                          )}
                        >
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__wu6EB
                            )}
                          >
                            {"Summer plants"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link___9Bcix
                            )}
                          >
                            {"Plants from Europe"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__mVanf
                            )}
                          >
                            {"Cactuses"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link___9NDEw
                            )}
                          >
                            {"Big plants"}
                          </a>
                        </p.Stack>
                      ) : null}
                    </div>
                  ) : null}
                </div>
                <div className={classNames(projectcss.all, sty.column__e9Gl9)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__iWMn)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__qRqIv)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__caYtx)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant6JpgC6L1C8MPjCoBpj,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__e4Wah
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___2JiD5
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___08P1C
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__xKyov
                          )}
                        >
                          {"Donec finibus"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ra4Ur
                          )}
                        >
                          {"bigplants"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__ohIlp
                          )}
                        >
                          {"$100.00"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__dn5Bd)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__e9Txh)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant1JpgJur1RNKmGbilj,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yOcx
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__c2AVe
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gXiz9
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__jpf1N
                          )}
                        >
                          {"Nulla suscipit"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ipZuf
                          )}
                        >
                          {"bigplants "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__tbZYv
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__mg9Np)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0Fuez)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant5JpgSC9Dn8R35Vnpr,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__qpNgQ
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___6EfbS
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bw4O7
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__s94Zl
                          )}
                        >
                          {"Vestibulum eget"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__icGp
                          )}
                        >
                          {"bigplants "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__rMDg2
                          )}
                        >
                          {"$220.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__zy8Pe)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__o9IoB)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant7JpgFY6MVzsllwIo2L,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eRgOh
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__uYpc
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__e8AZz
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__jLuF
                          )}
                        >
                          {"Sed consectetur"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__k2FgC
                          )}
                        >
                          {"bigplants "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__onS3
                          )}
                        >
                          {"$18.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__brkRl)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dmyKa)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant6JpgC6L1C8MPjCoBpj,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gnbck
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ucr50
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___6U3Gf
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__rbPa
                          )}
                        >
                          {"Donec finibus"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3VkIe
                          )}
                        >
                          {"bigplants"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__r5Byl
                          )}
                        >
                          {"$100.00"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__iJwYc)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ztkia)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant2WebpSbSmpYgIseSxK,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pHXxr
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__aPsMn
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vSwSt
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__xymYg
                          )}
                        >
                          {"Integer porta"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2NOdg
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___7Pxxf
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__zPjFf)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__grY9A)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant41JpgPDx9Qa5KrKmFe,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__itYy9
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__in5XE
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nBeSi
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__twUZ
                          )}
                        >
                          {"Cras molestie"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ynLct
                          )}
                        >
                          {"cactuses "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__gHAvk
                          )}
                        >
                          {"$24.99"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__hy6Y)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___4DpU)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant31JpgVmNfGCgklisJox,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lCOe5
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__i2IxD
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kRso2
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__vIlbX
                          )}
                        >
                          {"Curabitur eu tempor"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hNv6K
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___951AE
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__bWmtf)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__pgZxr)}
                        displayHeight={
                          "270px /* plasmic-token: ObHWhBbrFxpNMB */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant9WebpKV5HjHwju5Oi,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__m6Gn2
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vU44Y
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xCm1I
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__sngS2
                          )}
                        >
                          {"Fusce sagittis"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kP2Po
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__srapG
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>
            </div>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"bigPlants"}
              data-plasmic-override={overrides.bigPlants}
              hasGap={true}
              className={classNames(projectcss.all, sty.bigPlants)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iWLw)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___5N5GB
                    )}
                  >
                    {"Big plants"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__wmWg)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__qoQwz)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___5Xjih)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant6JpgC6L1C8MPjCoBpj,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__oGfmZ)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__ne3Ey)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__upRye)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__e2AGp
                      )}
                    >
                      {"Donec finibus"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8YbJg
                      )}
                    >
                      {"bigplants"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___6S2Ut
                      )}
                    >
                      {"$100.00"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__qzyC)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__muT9U)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant1JpgJur1RNKmGbilj,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__awjn3)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__nf437)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9PFsX)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__zoVI
                      )}
                    >
                      {"Nulla suscipit"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sAm7N
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__yUhxt
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column___7Xu9U)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qsTe0)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant7JpgFY6MVzsllwIo2L,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__iTLgy)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__tVtWo)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__r4Owb)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__uQ0L7
                      )}
                    >
                      {"Sed consectetur"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zYpP4
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__cbkow
                      )}
                    >
                      {"$18.40 "}
                    </h5>
                  </div>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___8Lxb0)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant5JpgSC9Dn8R35Vnpr,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tCyEz)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__dgG6Y)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__uJlwM)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___9CVjD
                      )}
                    >
                      {"Vestibulum eget"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__juEJt
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__c50Nt
                      )}
                    >
                      {"$220.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"cactuses"}
              data-plasmic-override={overrides.cactuses}
              hasGap={true}
              className={classNames(projectcss.all, sty.cactuses)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dGwzJ)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__eceDr
                    )}
                  >
                    {"Cactuses"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__srfTa)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__rMqLr)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qX8Et)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant41JpgPDx9Qa5KrKmFe,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kHCj)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___5AY)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__srUpz)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__mSr6R
                      )}
                    >
                      {"Cras molestie"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aeaAl
                      )}
                    >
                      {"cactuses "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__k4MIx
                      )}
                    >
                      {"$24.99"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__lTQn)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__oHcSu)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant31JpgVmNfGCgklisJox,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__guRuB)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__ePUr)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dRg8I)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__gtcZ5
                      )}
                    >
                      {"Curabitur eu tempor"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tSOyr
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__hhDex
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__sGxR)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__anwr)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant9WebpKV5HjHwju5Oi,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sPxHb)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__ll0Ez)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dRvFp)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__wXvJl
                      )}
                    >
                      {"Fusce sagittis"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__chKij
                      )}
                    >
                      {"Fusce sagittis"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__bjnfs
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__dJi8)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ocoKe)}
                    displayHeight={"270px /* plasmic-token: ObHWhBbrFxpNMB */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant2WebpSbSmpYgIseSxK,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bxgKs)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__hcUeJ)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oesGt)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__utauz
                      )}
                    >
                      {"Integer porta"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wnhmu
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___2LUDn
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__gLkB)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg___9Yap)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__y5ODg
                  )}
                >
                  {"Best sellers"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>
          <Footer className={classNames("__wab_instance", sty.footer__hvWzT)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "header2",
    "featureItem",
    "allProduct",
    "bigPlants",
    "cactuses",
    "bestSellers",
    "productRow"
  ],

  header: ["header", "header2", "featureItem"],
  header2: ["header2"],
  featureItem: ["featureItem"],
  allProduct: ["allProduct"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicStore__ArgProps,
          internalVariantPropNames: PlasmicStore__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStore__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStore";
  } else {
    func.displayName = `PlasmicStore.${nodeName}`;
  }
  return func;
}

export const PlasmicStore = Object.assign(
  // Top-level PlasmicStore renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    header2: makeNodeComponent("header2"),
    featureItem: makeNodeComponent("featureItem"),
    allProduct: makeNodeComponent("allProduct"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    // Metadata about props expected for PlasmicStore
    internalVariantProps: PlasmicStore__VariantProps,
    internalArgProps: PlasmicStore__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStore;
/* prettier-ignore-end */
