// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ozcq8GxerrF1WYaqjsW34y
// Component: 9S_qTaYwkjYj0t
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: ozcq8GxerrF1WYaqjsW34y/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: 9S_qTaYwkjYj0t/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: frBLqQ705DWxAc/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicRatings__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "stars",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.stars
      }
    ],

    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant($state, "stars", "five"),
          [sty.rootstars_four]: hasVariant($state, "stars", "four"),
          [sty.rootstars_one]: hasVariant($state, "stars", "one"),
          [sty.rootstars_three]: hasVariant($state, "stars", "three"),
          [sty.rootstars_two]: hasVariant($state, "stars", "two"),
          [sty.rootstars_zero]: hasVariant($state, "stars", "zero")
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant($state, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__bpvae, {
              [sty.svgstars_five__bpvae4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_zero__bpvaeef36N]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__xU7L, {
              [sty.svgstars_five__xU7L4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__xU7LnqPey]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__xU7LgJeor]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__xU7LtmVe6]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__xU7LWsbrk]: hasVariant($state, "stars", "two"),
              [sty.svgstars_zero__xU7Lef36N]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__h1NMc, {
              [sty.svgstars_five__h1NMc4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__h1NMcNqPey]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__h1NMcGJeor]: hasVariant(
                $state,
                "stars",
                "one"
              ),
              [sty.svgstars_three__h1NMctmVe6]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__h1NMcWsbrk]: hasVariant(
                $state,
                "stars",
                "two"
              ),
              [sty.svgstars_zero__h1NMcef36N]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__ud9X, {
              [sty.svgstars_five__ud9X4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__ud9XNqPey]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__ud9XGJeor]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__ud9XtmVe6]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__ud9XWsbrk]: hasVariant($state, "stars", "two"),
              [sty.svgstars_zero__ud9Xef36N]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__bJk2, {
              [sty.svgstars_five__bJk24E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__bJk2NqPey]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__bJk2GJeor]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__bJk2TmVe6]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__bJk2Wsbrk]: hasVariant($state, "stars", "two"),
              [sty.svgstars_zero__bJk2Ef36N]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__xFpoX, {
              [sty.svgstars_five__xFpoX4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__xFpoXnqPey]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__xFpoXgJeor]: hasVariant(
                $state,
                "stars",
                "one"
              ),
              [sty.svgstars_three__xFpoXtmVe6]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__xFpoXWsbrk]: hasVariant(
                $state,
                "stars",
                "two"
              ),
              [sty.svgstars_zero__xFpoXef36N]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__y7IPy, {
              [sty.svgstars_five__y7IPy4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__y7IPynqPey]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_three__y7IPYtmVe6]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__y7IPyWsbrk]: hasVariant($state, "stars", "two")
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___7NnJu, {
              [sty.svgstars_five___7NnJu4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four___7NnJunqPey]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_three___7NnJUtmVe6]: hasVariant(
                $state,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__jLEwi, {
              [sty.svgstars_five__jLEwi4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__jLEwiNqPey]: hasVariant(
                $state,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant($state, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__mbk9B, {
              [sty.svgstars_five__mbk9B4E3Za]: hasVariant(
                $state,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>
      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
